### ISSUE TITLE
How to use custom "App" extensions

### ISSUE THREAD

**Issue by RustyKnight** [intentkit/IntentKit#48]
i download the demo source code and was able to introduce two new intents for handling phone numbers, "call" and "message"

These are currently included in the demo source base I have locally.

Now I'm curious about how I might get these included in my projects. I'm assuming I can install the IntentKit via pods on my project and simply included the required source files and properties files in a "App" directory in my source and the IntentKit pick it up

**Comment by lazerwalker** [comment]
I'm assuming this is implemented as some sort of `INKHandler` subclass?

If you're looking for the simplest thing that will work, installing IntentKit via CocoaPods and manually adding your source/plist files into your project should do the trick.

Alternatively, you could create your own CocoaPod containing your extension and have it require the IntentKit core. There are lots of instructions on http://guides.cocoapods.org to help you get set up with that. If you don't want your extension to be a public pod, there are also instructions for setting it up as a private pod.

Finally, if you think this is something potentially helpful to other people, you could consider submitting your new handlers as a pull request. Without knowing the details of what you've made I don't have strong opinions on it, but if it's suitably generic I could see the case for adding it to IntentKit proper for others to use.

**Comment by lazerwalker** [comment]
Did you ever figure this out?

I'm going to close this issue for now, but happy to answer any more questions you might have.

**Comment by RustyKnight** [comment]
I've just come back to it and no, I've not been able to get it to work (I've been able to make it work in the demo though).

I've tried adding my "handlers", .plists and images to my project, installing IntentKit via pods.  It doesn't seem to be able to find the "bundle"

I then tried adding my extension to the pod (which is installed in my project), but then it couldn't find the header.

I'll make a pull request and see if we can get that to work

**Comment by lazerwalker** [comment]
To be clear, you're trying to create a new handler (e.g. `INKPhoneHandler`), not add a new application that supports an existing handler?

Come to think of it, it will need to be inside the pod. Because of the way Xcode/CocoaPods deal with embedding art assets/etc from linked xcodeprojects, IntentKit has handling code that does expect any included images to be in a resource bundle managed by IntentKit rather than your own project.

To add your own code/assets/etc to the pod, you won't be able to just drag them into Xcode, you'll also need to add them to the Podspec. See the existing subspaces in there (https://github.com/intentkit/IntentKit/blob/master/IntentKit.podspec) as an example of how to do that.

**Comment by RustyKnight** [comment]
Thanks for the update. Yes, I've created a new handler for two "Apps" (Phone and Messanger)

I will have a look at the link and see what I can figure out

**Comment by RustyKnight** [comment]
I've had a (really) quick look over the code that cocoapods installed into my project but there is no podspec file.  The documentation of cocoapods is also a little light and scattered, is there away to "re-build" the pod within the project once it's been "installed"?
